### ISSUE TITLE
resize of output univector bug

### ISSUE THREAD

**Issue by mipac** [kfrlib/kfr#110]
using pure univector and ref univector don't present the same behaviour
```c++
std::vector<float> out;
std::vector<float> in = {1, 2, 3};
auto uout = make_univector(out);
auto uin = make_univector(in);

//for example with a filter_fir<float>
myfilter.apply(uout, uin);
```
uout, and so out, are empty, not resized
but if I use 
```c++
univector<float> out;
univector<float> in = {1, 2, 3};
```

out.size() == in.size() is ok
is it a bug, or a correct behaviour?

**Comment by samuelriddle** [comment]
Hi,
It's expected behavior because `univector` created using `make_univector` only reads/writes data referenced and doesn't modify the container itself (std::vector in your case) because after creation it doesn't even know the original type.

It's intended mainly for avoiding redundant data copy and using kfr expressions directly on your data without creating temporary `univector`.
Example:
```c++
void process_gain(float* data, size_t size, float gain)
{
    auto buf = make_univector(data, size); // no data copy
    buf *= gain; // operates directly on data
}
```

So when using any container except `univector` you're responsible for setting the correct size before processing.
