### ISSUE TITLE
Documentation: what is the amplitude of the fft real complex?

### ISSUE THREAD

**Issue by abique** [kfrlib/kfr#5]
Hi,

I wonder what is computed exactly, because I get much lower volume than FFTReal or KissFFT.

Do you already divide the elements by 1/N?

Regards,
Alex.

**Comment by abique** [comment]
By the way I'm trying with the master, because the version 1.2 did crash clang 3.9.0.

**Comment by abique** [comment]
For example here: http://www.fftw.org/doc/The-1d-Real_002ddata-DFT.html#The-1d-Real_002ddata-DFT it is clear what I'll get for the amplitude.

**Comment by dlevin256** [comment]
Hi,

No division is performed on the output of FFT, neither for forward nor for backward transform.

The following code outputs the result which is identical to the output of the fft function from numpy.

```c++
// C++, KFR
const dft_plan_real<double> dft(1024);
univector<u8> temp(dft.temp_size);

univector<double, 1024> input = cos(linspace(0.0, 2 * constants<double>::pi, 1024));
univector<complex<double>, 512 + 1> output;
dft.execute(output, input, temp);    
println(output);
// 512 + -1.18128e-013j
```
```python
# python, numpy
import numpy as np
data = np.cos(np.linspace(0, np.pi * 2, 1024, endpoint=False))
fdata = np.fft.fft(data)
print fdata[1]
# (512-2.73953068846e-13j)
```

As you can see, the output is almost identical.

**Comment by abique** [comment]
numpy is doing a division in the inverse fft isn't it?

https://docs.scipy.org/doc/numpy/reference/routines.fft.html#normalization

**Comment by dlevin256** [comment]
As for the algorithm itself, real FFT is used for FFT convolution and is certainly tested in KFR.

KFR doesn't perform a division as part of the inverse FFT.

How do you obtain that results?
In order to check it all, please provide the minimal code that reproduces your result.
Also, provide the code where you call FFTReal and KissFFT for comparison.

Did you get lower volume after forward FFT or after backward FFT?

And run the above code snippet and check that the result is (512, 0).
