### ISSUE TITLE
[Feature Request] Dynamic Library Creation

### ISSUE THREAD

**Issue by acxz** [kfrlib/kfr#58]
Having kfr create a dynamic library (.so) during the build process, would make codebases that depend on kfr have more flexibility instead of static libraries (.a) that are currently built. Having both shouldn't be a problem either.

**Comment by dlevin256** [comment]
Building KFR DFT as a shared library with C interface is in progress.

Moreover, CMake has built-in feature for building shared libraries instead of static ones https://cmake.org/cmake/help/latest/variable/BUILD_SHARED_LIBS.html

**Comment by dlevin256** [comment]
Building shared libraries works as expected.
```
mkdir build
cd build
cmake -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTS=ON ..
make -j14
ls *.so
libkfr_dft.so  libkfr_io.so
ldd bin/dft
...
libkfr_dft.so => .../libkfr_dft.so (...)
...
```
Also works with make install.
Tested using `dev` branch.

**Comment by acxz** [comment]
I was hoping the shared library would be built automatically through the the cmake build and install process instead of manually specifying it. Is there a particular reason why the static library is the default instead of the dynamic library?

**Comment by dlevin256** [comment]
In 4.0 version, there is KFR C API can be enabled using
`-DENABLE_CAPI_BUILD=ON` flag for cmake.
It builds `kfr_capi` shared library that can be used by any compiler/language capable of calling c functions.

> Is there a particular reason why the static library is the default instead of the dynamic library?
The reason is to make using KFR with cmake as much transparent as possible, thus not overriding any cmake variables with non-default values.
