### ISSUE TITLE
resample streaming

### ISSUE THREAD

**Issue by mipac** [kfrlib/kfr#72]
Hi,
Could you give me an example showing resampling a stream of samples?

best regards,

**Comment by dlevin256** [comment]
Hi,
Here is an example of resampling. It processes audio by blocks in cycle.
Cycle body is what should be done in your block processing function.
https://github.com/kfrlib/kfr/blob/master/tools/sample_rate_converter.cpp

Because with resampling the sizes of input and output buffers differ, there are two different approaches:
* Fixed size of input block, size of output block is determined from the size of input block.
* Fixed size of output block, size of input block is determined from the size of output block.

Both are possible with KFR using `output_size_for_input` and `input_size_for_output` functions.

Note that resampler has delay, `get_fractional_delay` function returns it (may be fractional).

**Comment by mipac** [comment]
I haven't seen that example... sorry for noise...

It's difficult to understand the use of univector, for example the use of .ref() after the slice() etc...
Do you have pointer to a tutorial about that fundamentals ?

best regards

**Comment by dlevin256** [comment]
`ref()` converts `univector<>&&` returned by slice() to `univector<>&` required by `resampler<>::process`. It's just requirement of C++.
